config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  resources :links do
    resources :comments
  end

  get 'articles', to:"links#news"
  
  get 'search', to: "links#search"
  get 'links', to: "links#index"
 
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  require 'news-api'
   # Active Storage from Rails 5
   has_one_attached :thumbnail
   has_one_attached :banner
   # Action Text from Rails 6
   has_rich_text :body
 
   validates :title, length: { minimum: 5 }
   validates :body,  length: { minimum: 25 }
 
  def self.search_by(search_term)
      where("LOWER(title) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end


   self.per_page = 10;
 
  
  def fetch_news_query query
    url = "https://newsapi.org/v2/everything?q=#{query}&apiKey=#{ENV['newsapi']}&language=en"
    response = HTTParty.get(url)
    response.parsed_response['link'] unless response.code != 200
  end
    
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links, class_name: "link", foreign_key: "reference_id"
  has_many :comments
         #gives username to user on posts
         def username
           return self.email.split('@')[0].capitalize
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_action :authenticate_user!

  def fetch_news
     url = "https://newsapi.org/v2/top-headlines?country=ie&apiKey=c0609dca0c634fcc91e201434ce569e1"
     response = HTTParty.get url
     @articles = response.parsed_response['articles'] unless response.code != 200
   end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_link
  before_action :authenticate_user!

  def create
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to link_path(@link)
  end

  def destroy
    @link = Link.find(params[:link_id])
    @comment = @link.comments.find(params[:id])
  @comment.destroy
  redirect_to link_path(@link)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :link_id)
  end

  def set_link
    @link = Link.find(params[:link_id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :fetch_news, only: [:news]
  require 'news-api'
  require 'open-uri'
  # GET /links
  # GET /links.json
  def index
    

     @links = Link.all.order("created_at DESC").paginate(page: params[:page])
     if params[:search]
      @search_term = params[:search]
      @links = @links.search_by(@search_term)
    end
    # placeholder for images that do not exist
    @image_placeholder = 'https://placehold.it/50x50'
    @articles ||= []

  end

  def articles
    

    newsapi = News.new("c0609dca0c634fcc91e201434ce569e1")             

# /v2/top-headlines
top_headlines = newsapi.get_top_headlines(q: 'corona',
                                          language: 'en',
                                          country: 'ie')

# /v2/everything
all_articles = newsapi.get_everything(q: 'news',
                                      sources: 'bbc-news,the-verge',
                                      domains: 'bbc.co.uk,techcrunch.com',
                                      from: '2020-03-28',
                                      language: 'en',
                                      sortBy: 'relevancy',
                                      page: 2)

# /v2/sources
sources = newsapi.get_sources(country: 'ie', language: 'en')
    # Init
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @comment = Comment.new
    @comments = @link.comments
    

    @link.views ||= 0
    @link.update(views: @link.views + 1)
    
   
    @image_placeholder = 'https://placehold.it/50x50'
  query = params[:q]
  @articles = fetch_news_query query unless !query
  @articles ||= [] # empty array if no query
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  def news
    @image_placeholder = 'https://placehold.it/50x50'
    query = params[:q]
    @articles = fetch_news_query query unless !query
    @articles ||= [] # empty array if no query

    newsapi = News.new("c0609dca0c634fcc91e201434ce569e1")             

    # /v2/top-headlines
    top_headlines = newsapi.get_top_headlines(q: 'news',
                                              language: 'en',
                                              country: 'ie')
    
   

  end


  def search
    # Get /links/search
  #@links = Link.where("title LIKE ?", params[:q])
  @image_placeholder = 'https://placehold.it/50x50'
  query = params[:q]
  @articles = fetch_news_query query unless !query
  @articles ||= [] # empty array if no query
end
  

  # GET /links/1/edit
  def edit
    @link.user = current_user
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user = current_user #setting the link to the current user logged in
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id]) 
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :id, :url, :search, :views, :body, :thumbnail, :banner)
    end

     def fetch_news_query query
       url = "https://newsapi.org/v2/top-headlines?country=ie&apiKey=c0609dca0c634fcc91e201434ce569e1"
       response = HTTParty.get url
       response.parsed_response['articles'] unless response.code != 200
     end

    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="Container">
<div class="row d-flex justify-content-center" style="width:100%">
      <div class="card mb-3">
        
        <div class="card-body">
          <p class="card-text">  <%= comment.body %> </p>
          
          
          <hr class="my-4" />
            <%= time_ago_in_words(comment.created_at)  %>
        
        
            <p><%= link_to 'Delete', [comment.link, comment], method: :delete, data: { confirm: 'Are you sure?' } %></p>
        
        
        
    </div>
    </div>
    </div>
    </div>

    
    

app/views/comments/_form.html.erb
<div class="row d-flex justify-content-center">
<%= form_for([@link,@link.comments.build]) do |f|%>
    <p>
        
        <%= f.text_area :body %>
    </p>
    <br>
    <P>
        <%= f.submit class:"btn btn-primary"%>
    </p>
    <%end%>
    </div>

    

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<% if action_name != "home" %>

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path%>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= new_link_path%>">Add Blog post </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= links_path%>">User Blogs</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= articles_path%>">Global news</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
    <% if current_user%>
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Account Settings", edit_user_registration_path, class:'dropdown-item'%> 
          <%= link_to "Password", edit_user_password_path, class:'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
        </div>
      </li>
    </ul>
    <% else %>
        <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
        </li>
    <% end %>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 



 
  </head>

  <body>

    <%= render 'layouts/navbar'%>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/links/_articles.html.erb
<div class="container">
  <div class ="row">
    <% @articles.each_with_index do |x, article_key| %>
      <div class="card col-lg-4 col-md-6 col-sm-12 article">

        <span 
          data-url="<%= x['url'] %>" 
          class="article-title" 
          id="article-<%= article_key %>"
          title="<%= x['title']%>" 
          style="font-weight: bold;"
        > 
            <%= x['title'] %>     
        </span>

        <span><%= x['source']['name'] %></span>
        <%= image_tag(x['urlToImage'] || @image_placeholder, class: 'card-img-top') %>  
        <div class="card-body">
          <h5 class="card-title"><% x['title'] %></h5>
          <p class="card-text"> <%= x['description'] %></p>
        </div>
        
      </div>
    <% end %>
  </div>  
</div>

app/views/links/_form.html.erb
<%= form_with model: link do |f| %>
  
  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string', placeholder: "Article title" %>
    <br>
    <%= f.text_field :url, class:'form-control string', placeholder: "Link to website" %>
    <br>
    <%= f.label :banner, class:'form-control' %>
    
    <%= f.file_field :banner, class:'form-control'%>
    <br>
    <%= f.rich_text_area :body, class:'form-control', placeholder: "Body of the article"%>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>
<% if user_signed_in? %>
  <% if @link.user.id == current_user.id %>
    <%= render 'form', link: @link %>
    <% end %>
    <% else %>
    <h1>you can't edit other peoples posts</h1>
    <% end %>
<%= link_to 'Show', @link %> 
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="container">
  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate @links, :container => false %>
    </div>
  </div>
<h1>Welcome to our user blog page, here you can make your own posts and discuss on current news</h1>
<h2><strong>Refine your search:</strong></h2><br>
<%= form_for "",url: links_path, role: "search", method: :get do %>
<%= text_field_tag :search, @search_term, placeholder: "Search..."%><br></n>
<%end%>
<br>
<br>

  <% @links.each do |link| %>
    <div class="row">
      <div class="card mb-3">
        
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to link.title, link %>
          </h5>
          <p class="card-text">
            <%= link.body.to_plain_text.truncate_words(50) %>
          </p>
          <p class="card-text">
            <small class="text-muted">
              <%= link.updated_at.strftime("%A, %B %e, %Y") %> by
              <%= link.user.username %> | <%= pluralize(link.views, "View") %>  
            </small>
          </p>
          <td><%= link_to 'Edit', edit_link_path(link) %></td>
          <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div>
  <br>
  <%= render 'articles' %>
  <footer id="news-api" class="text-center footer">
      <p>Powered by <a href="https://newsapi.org/">News Api</a></p>
    </footer> 
</div>

app/views/links/new.html.erb
<h1>Add your article here</h1>
<br>
<%= render 'form', link: @link %>
<br>
<%= link_to 'Back', links_path, class:"btn btn-primary" %>

app/views/links/news.html.erb
<h1 class="text-center">Top Headlines</h1>
<%= render 'articles'%>

app/views/links/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
  <%= image_tag(@link.banner, style:'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">
      <h1 class="display-4">
        <%= link_to @link.title, root_path %>
      </h1>

      <p class="lead">
      <%-#found @ https://devhints.io/strftime-%>
        <%= @link.updated_at.strftime("%A, %B %e, %Y") %> by <%= @link.user.username %> | <%= pluralize(@link.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @link.body %>
      </div>
    </div>
  </div>
</div>

<div class="container">
<h2> <%= @link.comments.count %> Comments</h2>
<br>
<%= render @link.comments%>
<h3>Add a comment</h3>
<%= render "comments/form" %>
<br>
</div>

app/views/pages/home.html.erb
<div class="Container">
    <div class="jumbotron">
        <h1 Class="display-4">Welcome to my news app</h1>
        <h2 class="display-4">Please sign in below or continue to our articles</h2>
    </div>
<% if current_user %>
<%= link_to "Sign out", destroy_user_session_path, class:"btn btn-primary", method: :delete %>


<% else %>
<%= link_to 'Sign in', new_user_session_path, class:"btn btn-primary" %>
<%= link_to 'Sign up', new_user_registration_path, class:"btn btn-primary" %>

<% end %>

<%= link_to 'Articles', links_path, class:"btn btn-primary" %>

    </div>
</div>